export default class RouterUrlConstantValue {
  // =================== 路由 URL ===================
  // 首页
  static readonly HOME_PAGE_URL:string = 'pages/HomePage'
  // 登录页-账号密码登录
  static readonly LOGIN_BY_ACCOUNT:string = 'pages/login/LoginByAccount'
  // 登录页-手机号
  static readonly LOGIN_BY_PHONE_NUMBER_STEP_ONE:string = 'pages/login/LoginByPhoneNumberStepOne'
  static readonly LOGIN_BY_PHONE_NUMBER_STEP_TWO:string = 'pages/login/LoginByPhoneNumberStepTwo'
  // 注册页
  static readonly REGISTER_PAGE:string = 'pages/register/RegisterPage'
  // 微信主页
  static readonly MAIN_PAGE:string = 'pages/MainPage'
}