export default class UIConstantValue {
  // =================== 宽高 ===================
  // 百分比
  static readonly HEIGHT_PERCENT_5: Percentage = '5%';
  static readonly WIDTH_PERCENT_22: Percentage = '22%';
  static readonly WIDTH_PERCENT_25: Percentage = '25%';
  static readonly WIDTH_PERCENT_35: Percentage = '35%';
  static readonly HEIGHT_PERCENT_35: Percentage = '35%';
  static readonly WIDTH_PERCENT_38: Percentage = '38%';
  static readonly WIDTH_PERCENT_50: Percentage = '50%';
  static readonly WIDTH_PERCENT_65: Percentage = '65%';
  static readonly WIDTH_PERCENT_80: Percentage = '80%';
  static readonly WIDTH_PERCENT_100: Percentage = '100%';
  static readonly HEIGHT_PERCENT_100: Percentage = '100%';
  // 数值
  static readonly WIDTH_1: string = '1vp';
  static readonly WIDTH_5: string = '5vp';
  static readonly HEIGHT_5: string = '5vp';
  static readonly WIDTH_10: string = '10vp';
  static readonly HEIGHT_10: string = '10vp';
  static readonly WIDTH_15: string = '15vp';
  static readonly HEIGHT_15: string = '15vp';
  static readonly WIDTH_12: string = '12vp';
  static readonly HEIGHT_12: string = '12vp';
  static readonly WIDTH_14: string = '14vp';
  static readonly HEIGHT_14: string = '14vp';
  static readonly WIDTH_18: string = '18vp';
  static readonly HEIGHT_18: string = '18vp';
  static readonly WIDTH_20: string = '20vp';
  static readonly HEIGHT_20: string = '20vp';
  static readonly WIDTH_25: string = '25vp';
  static readonly HEIGHT_25: string = '25vp';
  static readonly WIDTH_28: string = '28vp';
  static readonly HEIGHT_28: string = '28vp';
  static readonly WIDTH_30: string = '30vp';
  static readonly HEIGHT_30: string = '30vp';
  static readonly WIDTH_32: string = '32vp';
  static readonly HEIGHT_32: string = '32vp';
  static readonly WIDTH_35: string = '35vp';
  static readonly HEIGHT_35: string = '35vp';
  static readonly WIDTH_36: string = '36vp';
  static readonly HEIGHT_36: string = '36vp';
  static readonly WIDTH_40: string = '40vp';
  static readonly HEIGHT_40: string = '40vp';
  static readonly WIDTH_45: string = '45vp';
  static readonly HEIGHT_45: string = '45vp';
  static readonly HEIGHT_50: string = '50vp';
  static readonly WIDTH_60: string = '60vp';
  static readonly HEIGHT_60: string = '60vp';
  static readonly WIDTH_62: string = '62vp';
  static readonly WIDTH_65: string = '65vp';
  static readonly HEIGHT_65: string = '65vp';
  static readonly WIDTH_75: string = '75vp'
  static readonly WIDTH_100: string = '100vp';
  static readonly HEIGHT_100: string = '100vp';
  // =================== 间距 ===================
  // space
  static readonly SPACE_5: string = '5vp'
  static readonly SPACE_8: string = '8vp'
  static readonly SPACE_10: string = '10vp';
  static readonly SPACE_15: string = '15vp';
  static readonly SPACE_20: string = '20vp';
  // padding
  static readonly PADDING_PERCENT_5: Percentage = '5%';
  static readonly PADDING_PERCENT_10: Percentage = '10%';
  static readonly PADDING_0: string = '0vp';
  static readonly PADDING_2: string = '2vp';
  static readonly PADDING_5: string = '5vp';
  static readonly PADDING_8: string = '8vp'
  static readonly PADDING_10: string = '10vp';
  static readonly PADDING_15: string = '15vp';
  static readonly PADDING_20: string = '20vp';
  static readonly PADDING_30: string = '30vp';
  // margin
  static readonly MARGIN_10: string = '10vp';
  // margin 百分比
  static readonly MARGIN_PERCENT_6: Percentage = '6%';
  static readonly MARGIN_PERCENT_7: Percentage = '7%'
  static readonly MARGIN_PERCENT_8: Percentage = '8%';
  static readonly MARGIN_PERCENT_12: Percentage = '12%'
  static readonly MARGIN_PERCENT_15: Percentage = '15%'
  static readonly MARGIN_PERCENT_50: Percentage = '50%'
  static readonly MARGIN_PERCENT_90: Percentage = '90%'
  static readonly MARGIN_PERCENT_95: Percentage = '95%'
  // =================== 边框 ===================
  static readonly BORDER_WIDTH_0_5: string = '0.5vp';
  static readonly BORDER_WIDTH_0_7: string = '0.7vp';
  static readonly BORDER_WIDTH_1: string = '1vp';
  static readonly BORDER_WIDTH_1_POINT_5: string = '1.5vp';
  static readonly BORDER_WIDTH_2: string = '2vp';
  // =================== layoutWeight ===================
  static readonly LAYOUT_WEIGHT_1: number = 1;
  // =================== 圆角 ===================
  static readonly BORDER_RADIUS_5: string = '5vp';
  static readonly BORDER_RADIUS_10: string = '10vp';
  static readonly BORDER_RADIUS_20: string = '20vp';
  static readonly BORDER_RADIUS_50: string = '50vp';
  static readonly BORDER_RADIUS_NUMBER_20: number = 20;
  // =================== 透明度 ===================
  static readonly Opacity_0_POINT_1: number = 0.1
  // =================== 偏移 ===================
  static readonly OFFSET_NEGATIVE_22: string = '-22vp';
  static readonly OFFSET_NEGATIVE_0_5: string = '-0.5vp';
  static readonly OFFSET_7: string = '7vp';
  static readonly OFFSET_PERCENT_30: Percentage = '30%'
  // =================== 选择角度 ===================
  static readonly ROTATE_ANGLE_45: number = 45;
}